### ISSUE TITLE
Add option to specify what Kernel to start

### ISSUE THREAD

**Issue by odewahn** [oreillymedia/thebe#12]
Right now, thebe starts a python kernel by default.  But, it would be nice to be able to also start other kinds of kernels, like `R` or `Julia` (or even a specific version of Python, like `python2` or `python3`).  

```
curl -d '{"name":"julia"}' http://192.168.59.103:8888/api/kernels
```

In Atlas, you might specify the kernel in the `data-code-language` attribute, like this:

```
<pre data-executable="true" data-code-language="julia">
```

**Comment by zischwartz** [comment]
You can specify this now in the thebe options, though of course it's only what the notebook server container has, i.e. `python2` or `python3`.

Moving forward though, how important/likely is it going to be for one page to contain multiple kernels? Jupyter can do this, with those %magic commands, but I worry about how this is going to work with dependencies and multiple containers.

**Comment by rgbkrk** [comment]
I'm guessing one page would only have a single kernel. Just ran into this, I'll dig into the options now.

**Comment by zischwartz** [comment]
`kernel_name` option works and is in master now so closing this

**Comment by rgbkrk** [comment]
Oh right, and I've been using it for > 3 months now.
