### ISSUE TITLE
CORS on tmpnb

### ISSUE THREAD

**Issue by rgbkrk** [oreillymedia/thebe#18]
Now that https://github.com/jupyter/tmpnb/pull/132 has been merged, is it ok to use the main tmpnb?

**Comment by zischwartz** [comment]
Till yesterday it was, but in order to get this working across browsers (specifically Safari 8) I had to change tmpnb's  `/spawn` route to respond with the url rather than do a redirect to the url. Because CORS in Safari doesn't like redirects.

**Comment by rgbkrk** [comment]
Ah, interesting.

How would you feel about an API endpoint? Consume `/api/spawn` programmatically, somehow?

**Comment by zischwartz** [comment]
That sounds great.

**Comment by zischwartz** [comment]
[Is this the direction](https://github.com/zischwartz/tmpnb/blob/spawn_api/orchestrate.py#L103-L125) you were thinking?

**Comment by rgbkrk** [comment]
Yup, that's perfect.

**Comment by zischwartz** [comment]
Should I put this in another PR? (The Spawn API stuff)

**Comment by rgbkrk** [comment]
Totally. You're definitely taking the right directions.
