### ISSUE TITLE
shift-space behavior

### ISSUE THREAD

**Issue by rgbkrk** [oreillymedia/thebe#33]
With the thebe currently on https://lambdaops.com/share-cell/, typing shift-space results in no space being inserted. On beta.oreilly.com, it ends up switching to the next cell. In the Jupyter notebook, it inserts a space. Same with most text boxes, like here on GitHub Issues.

Is there a way to make it insert a space when shift-space is hit? (Yes this is accommodation for greedy shift-pressers like me.)

**Comment by rgbkrk** [comment]
Now I see that it's part of the docs in the README. Whoops!

I guess this is my humble request to be able to override that binding.

**Comment by zischwartz** [comment]
Haha, no problem, yeah, I'll add an option to disable/reassign it.

**Comment by rgbkrk** [comment]
:smile:

Now that I'm thinking about it again, I've got to ask what the motivation is for that binding. I feel like if I hit this on a thebe-enabled page I'd get rather confused about being switched to the next cell.

**Comment by zischwartz** [comment]
Yeah, `space` is far from an ideal key for this. `tab` would be more natural, but has a lot of behaviors built into the code_cells already, as does `down-arrow`.

Totally open to other suggestions, or we could just disable it by default.

Also, I'm adding a way to modify they key (or disable it) right now. :8ball:
