### ISSUE TITLE
Configure the CodeMirror modeURL

### ISSUE THREAD

**Issue by rgbkrk** [oreillymedia/thebe#38]
Right now, only Python gets bundled in as a CodeMirror mode. The mode URL needs to be [set for codemirror to pick up its modes](http://codemirror.net/doc/manual.html#addon_loadmode). This could be done by adapting to the rawgit URL you have right now (because the js is bundled):

``` JavaScript
CodeMirror.modeURL = "https://rawgit.com/oreillymedia/thebe/master/static/components/codemirror/mode/%N/%N.js";
```

CodeMirror with then replace the %Ns with the right language:

[Ruby](https://rawgit.com/oreillymedia/thebe/master/static/components/codemirror/mode/ruby/ruby.js)
[R](https://rawgit.com/oreillymedia/thebe/master/static/components/codemirror/mode/r/r.js)

**Comment by zischwartz** [comment]
Good call. 

I just spent a few minutes trying, but I can't figure out where to set this for it to actually take effect.

Update: I think the issue is [here](https://github.com/oreillymedia/thebe/blob/master/static/notebook/js/codecell.js#L131).

**Comment by zischwartz** [comment]
[This](https://github.com/codemirror/CodeMirror/issues/3320) seems to be related too. 

Guhh requirejs why you gotta make things so hard.

**Comment by rgbkrk** [comment]
;)

Soon we can build thebe from the ground up using https://github.com/jupyter/jupyter-js-output-area and https://github.com/jupyter/jupyter-js-services

**Comment by zischwartz** [comment]
Woah, very interesting

**Comment by rgbkrk** [comment]
Yeah this is what I was hoping to chat with you about. :wink:

**Comment by rgbkrk** [comment]
We still have some work to decouple widgets/comms from the notebook but we'll get there.

Most importantly, we'll be able to put the output areas in iframes to protect the rest of the page.

**Comment by zischwartz** [comment]
I just went ahead and bundled a bunch of common languages with thebe for simplicity, and because it really doesn't add much as far as the footprint (like 15kb).

**Comment by rgbkrk** [comment]
:+1:
