### ISSUE TITLE
Errors in narratives

### ISSUE THREAD

**Issue by rgbkrk** [oreillymedia/thebe#39]
There are times when an author wants to convey errors to a reader.

![screenshot 2015-06-02 08 16 53](https://cloud.githubusercontent.com/assets/836375/7936620/234e54b8-0900-11e5-832a-341499980eb5.png)

In cases like these, with the default "It looks like there was an error. You might need to run the code examples above for this one to work.", it makes the narrative a bit confusing.

The hard part that thebe and a reader faces is that they skim through the content not running a cell until midway through the page (or only certain cells), when in fact there is an intended flow.

It seems like we need thebe to be able to:
- Recognize the intended flow of cells (have they run all dependent cells?)
- Run a subsection of cells based on running one deep inside

Alternatively, we need a particular kernel state at a given point in the cells. There's not a communication layer that can give us this yet. I'm imagining some way of asking the kernel if we're in the right state. This could be intractable though.

**Comment by zischwartz** [comment]
Good point.  But yeah, I'm not sure what a good/reasonable/not-crazy-complicated solution to figuring out dependent cells would be.

A very simple and incomplete fix would be to just add an option that disables that message about the error, so if you're creating some content that's going to explain a lot about error handling, you can at least save the user that confusion.

**Comment by zischwartz** [comment]
Closed this for now, but feel free to reopen it.
