### ISSUE TITLE
Bower install process is undocumented

### ISSUE THREAD

**Issue by ngoldbaum** [oreillymedia/thebe#59]
I'm new to javascipt development and had no idea how to set up the `static/components` directory when I tried to set up an example using thebe just now.

I think I have it sorted after getting node and bower set up, but it wasn't obvious how to do this based on what's in the readme right now.

**Comment by zischwartz** [comment]
Sorry about that, it's sort of in flux right now, we spent some time last week updating Thebe to use the new jupyter front end code, and I should not have pushed that to master without documenting it first. 

Documentation forthcoming.

**Comment by ngoldbaum** [comment]
I added a point in the install docs about this so I'm closing. Could probably be expanded but at least now it will be clear what needs to be installed and what commands need to be run.
