### ISSUE TITLE
Cannot run example

### ISSUE THREAD

**Issue by ngoldbaum** [oreillymedia/thebe#60]
I'm trying to get the demo in the root of the thebe repository to work so I can then modify it for my needs.

I have an IPython notebook server (notebook version 4.0.4) launched with `--NotebookApp.allow_origin=*` running on http://localhost:8888/ in the root of the thebe repository. I also have python's SimpleHTTPServer running on port 8000 in the root of the thebe repository.

I've also made the following modification to index.html:

``` diff
diff --git a/index.html b/index.html
index cc4abce..69c5685 100644
--- a/index.html
+++ b/index.html
@@ -67,7 +67,8 @@
           // To run this locally, replace this url with the url of your notebook server or tmpnb server
           thebe = new main.Thebe({
             // url:"https://tmp39.tmpnb.org",
-            url:"https://192.168.99.100:8000",
+            // url:"https://192.168.99.100:8000",
+            url:"https://localhost:8888",
             // tmpnb_mode: false
           });
           // thebe = new main.Thebe({url:"https://tmp39.tmpnb.org"});
```

When I connect to https://localhost:8000, the demo page loads as expected. However, when I click the "run" button, the button says "starting server" for a while and then eventually disappears. I then have the following in my javascript console:

![image](https://cloud.githubusercontent.com/assets/3126246/10347407/4ca318c8-6cf9-11e5-8fa9-860ae4fa5538.png)

**Comment by zischwartz** [comment]
If you're using it with a notebook server directly, you'll want `tmpnb_mode` to be set to false.

Also, it looks like you're trying to connect to the notebook via `https` rather than `http`, which it seems like your notebook server isn't running on.

**Comment by ngoldbaum** [comment]
Thanks for the quick responses Zach!

Unfortunately it's not quite working yet. I've modified the url to use http and I've also set tmpnb_mode to false, but now I get the following errors:

![image](https://cloud.githubusercontent.com/assets/3126246/10350166/057f10aa-6d08-11e5-8069-04901fefe4bc.png)

Could this be because I'm not using the version of the notebook javascript that thebe is expecting?

**Comment by zischwartz** [comment]
Yeah, that looks like jupyter/notebook#522

**Comment by ngoldbaum** [comment]
Sorry, what would the fix for me be? I guess making sure I'm only using python3.

Does thebe support python3 kernels only?

I'm going to try again using a python3 virtualenv...

**Comment by ngoldbaum** [comment]
Nope, doesn't work with a python3 kernel either.

**Comment by ngoldbaum** [comment]
OK, I'm no longer getting a 405 error if I start the notebook server with "python3 -m notebook", but now I get a 404 error. My notebook server prints the following error message:

```
[W 16:04:31.902 NotebookApp] Blocking Cross Origin API request.  Origin: http://localhost:8000, Host: localhost:8888
[W 16:04:31.904 NotebookApp] 404 OPTIONS /api/kernels (::1) 2.41ms referer=http://localhost:8000/
```

**Comment by ngoldbaum** [comment]
Oops, never mind, I had incorrectly launched my notebook server without `--NotebookApp.allow_origin='*'`. Now I'm getting a 405 error on /api/kernels again

**Comment by mpacer** [comment]
Just as a heads up — this might have been a recent change in the jupyter library, because previously https://github.com/michaelpacer/thebe-test worked, and now it's giving the same error when I try to access the notebook from http://michaelpacer.github.io/thebe-test/. 

Not sure exactly why this is happening, but I'm going to try to work on figuring it out…

**Comment by ngoldbaum** [comment]
@michaelpacer try running the "notebook" package from the current git master branch.

**Comment by mpacer** [comment]
That works! thanks for the heads up
