### ISSUE TITLE
Change syntax highlighting theme

### ISSUE THREAD

**Issue by betatim** [oreillymedia/thebe#75]
Is there an easy way to change the theme used for the syntax highlighting? Each cell contains the following:

``` html
<div class="CodeMirror cm-s-default">
```

so it is using the default CM theme (though even for that the actual CSS seems to be missing from the examples). I can't find where to change to a different theme (or where to change the CSS so the default theme looks different).

**Comment by betatim** [comment]
Found it in `thebe/static/notebook/js/codecell.js` around line 130.

**Comment by zischwartz** [comment]
I've been meaning to hack this in as an option in thebe, so reopening this

**Comment by betatim** [comment]
Merci, I send :cake:.
